// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvndgrbclfavulineazs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2bmRncmJjbGZhdnVsaW5lYXpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTAyMzUsImV4cCI6MjA1OTQyNjIzNX0.duXU2wP6CUj-Mgky9VoXSt9yqbq1nvH5Lgg1fE1GZC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);